# Generated by Django 3.0.4 on 2020-04-27 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("article_id", models.TextField()),
                ("date", models.DateField(default=datetime.date.today, verbose_name="Date")),
                ("section", models.CharField(max_length=100)),
                ("headline", models.TextField()),
                ("url", models.TextField()),
                ("article", models.TextField()),
            ],
            options={"ordering": ("date",),},
        ),
        migrations.AlterField(model_name="tweet", name="tweet", field=models.TextField(),),
    ]
